// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ZeFiveNime.Migrations
{
    [DbContext(typeof(ZeFiveNimeDbContext))]
    [Migration("20241106040115_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZeFiveNime.Models.Animation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("PosterByte")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tahun")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Animation");
                });

            modelBuilder.Entity("ZeFiveNime.Models.Episode", b =>
                {
                    b.Property<int>("Id_Episode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Episode"));

                    b.Property<int>("Durasi")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Animation")
                        .HasColumnType("integer");

                    b.Property<string>("Judul_Episode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id_Episode");

                    b.HasIndex("Id_Animation");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("ZeFiveNime.Models.Source", b =>
                {
                    b.Property<int>("Id_Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Source"));

                    b.Property<int>("Episode_SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name_Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceOne")
                        .HasColumnType("text");

                    b.Property<string>("SourceThree")
                        .HasColumnType("text");

                    b.Property<string>("SourceTwo")
                        .HasColumnType("text");

                    b.HasKey("Id_Source");

                    b.HasIndex("Episode_SourceId");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("ZeFiveNime.Models.Episode", b =>
                {
                    b.HasOne("ZeFiveNime.Models.Animation", "Animation")
                        .WithMany("Episodes")
                        .HasForeignKey("Id_Animation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animation");
                });

            modelBuilder.Entity("ZeFiveNime.Models.Source", b =>
                {
                    b.HasOne("ZeFiveNime.Models.Episode", "Episode")
                        .WithMany("Sources")
                        .HasForeignKey("Episode_SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("ZeFiveNime.Models.Animation", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("ZeFiveNime.Models.Episode", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
